repos:
  - repo: local
    hooks:
      - id: poe-check-markdown
        name: poe check markdown
        language: system
        entry: uv run poe check-markdown
        types: [markdown]
        pass_filenames: false
      - id: poe-check-python
        name: poe check python
        language: system
        entry: uv run poe check-python
        types: [python]
        pass_filenames: false
