[project]
name = "melyuh-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-awesome-pages-plugin>=2.10.1",
    "mkdocs-git-authors-plugin>=0.10.0",
    "mkdocs-git-revision-date-localized-plugin>=1.5.1",
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-macros-plugin>=1.3.7",
    "mkdocs-material[imaging]>=9.7.6",
    "mkdocs-mermaid-to-svg>=1.3.0",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-svg-to-png>=1.1.1",
    "mkdocs-table-reader-plugin>=3.1.0",
    "mkdocs-to-pdf>=0.11.2",
    "playwright>=1.59.0",
    "weasyprint>=62.3",
]

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "poethepoet>=0.46.0",
    "pre-commit>=4.6.0",
    "ruff>=0.15.13",
    "types-requests>=2.32.0",
    "types-Pygments>=2.18.0",
]

[tool.poe.tasks]
lint-markdown = "pnpm exec markdownlint-cli2 --fix '**/*.md' '!node_modules/**' '!.venv/**'"
format-markdown = "pnpm exec prettier --write '**/*.md' --ignore-path .gitignore --ignore-path .prettierignore"
check-markdown = [
    "lint-markdown",
    "format-markdown"
]
lint-python = "uv run ruff check --fix ."
type-check-python = "uv run mypy ."
format-python = "uv run ruff format ."
check-python = [
    "lint-python",
    "type-check-python",
    "format-python"
]

[[tool.mypy.overrides]]
module = ["mkdocs_to_pdf.*", "weasyprint"]
ignore_missing_imports = true
