"""PDF レンダリング前処理・デュアル PDF 生成"""

import logging
import os
import re
import shutil
from pathlib import Path

from _pdf.icon_fill import (
    fix_converted_arrow_fill,
    fix_converted_inline_icon_fill,
    fix_converted_twemoji_fill,
)
from _pdf.palette import PDF_LOGO_CONFIG, build_palette_css

log = logging.getLogger("mkdocs.hooks.build_config")


def write_if_changed(path: str, content: str) -> None:
    existing = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            existing = f.read()
    if existing != content:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)


def generate_pdf_styles(template_dir: str, pdf_scheme: str) -> None:
    """PDF スキームに合わせたテキスト色を styles.scss に出力する"""
    is_dark = pdf_scheme == "slate"
    fg = "hsla(0,0%,100%,.87)" if is_dark else "hsla(0,0%,0%,.87)"
    fg_light = "hsla(0,0%,100%,.54)" if is_dark else "hsla(0,0%,0%,.54)"

    scss = f"""// Auto-generated by hooks/build_config.py (PDF_SCHEME={pdf_scheme})
// ── ウェブサイト: スキームごとにアイコン色を制御 ──
[data-md-color-scheme="default"] .md-source-file,
[data-md-color-scheme="default"] .md-source-file__fact,
[data-md-color-scheme="default"] .md-source-file__fact .md-icon,
[data-md-color-scheme="default"] [class*="git-revision-date-localized-plugin"] {{
  color: hsla(0,0%,0%,.54);
}}
[data-md-color-scheme="slate"] .md-source-file,
[data-md-color-scheme="slate"] .md-source-file__fact,
[data-md-color-scheme="slate"] .md-source-file__fact .md-icon,
[data-md-color-scheme="slate"] [class*="git-revision-date-localized-plugin"] {{
  color: hsla(0,0%,100%,.54);
}}
// ── PDF 専用 (@media print) ──
@media print {{
  .md-source-file,
  .md-source-file__fact,
  .md-source-file__fact .md-icon,
  [class*="git-revision-date-localized-plugin"] {{
    color: {fg_light};
  }}
  article#doc-toc > h1,
  article#doc-toc li > a {{
    color: {fg} !important;
  }}
}}
"""
    os.makedirs(template_dir, exist_ok=True)
    styles_path = os.path.join(template_dir, "styles.scss")
    write_if_changed(styles_path, scss)
    log.info(f"to-pdf: styles.scss generated ({pdf_scheme}) → {styles_path}")


def pre_pdf_render(
    html_string: str,
    pdf_scheme: str,
    schemes: list,
    blog_post_articles: list,
) -> str:
    """WeasyPrint レンダリング直前に HTML を加工する。"""
    from bs4 import BeautifulSoup

    soup = BeautifulSoup(html_string, "html.parser")

    for a in soup.find_all("a", href=True):
        if a.find("img"):
            del a["href"]

    text_fill = (
        "rgba(255,255,255,0.82)" if pdf_scheme == "slate" else "rgba(0,0,0,0.87)"
    )
    fix_converted_inline_icon_fill(soup, text_fill)
    log.info(f"pre_pdf_render: inline icon fill set to {text_fill}")

    grid_fill = "#1a1a1a" if pdf_scheme == "slate" else "#ffffff"
    fix_converted_twemoji_fill(soup, grid_fill)
    log.info(f"pre_pdf_render: grid card title icon fill set to {grid_fill}")

    arrow_fill = next(
        (p["main"] for s, p, _ in schemes if s == pdf_scheme),
        "#26C6DA",
    )
    fix_converted_arrow_fill(soup, arrow_fill)
    log.info(f"pre_pdf_render: arrow icon fill set to {arrow_fill}")

    # nav 外ブログ記事を PDF に注入し、目次エントリも追加する
    toc_ul = None
    toc_article = soup.find("article", id="doc-toc")
    if toc_article:
        toc_ul = toc_article.find("ul")

    for article_html in blog_post_articles:
        article_soup = BeautifulSoup(article_html, "html.parser")
        section = article_soup.find(["section", "article"])
        if not section:
            continue

        if soup.body:
            soup.body.append(section)
        log.info(f"pre_pdf_render: injected blog post {section.get('id', '')}")

        if not toc_ul:
            continue

        h1 = section.find("h1")
        if not (h1 and h1.get("id")):
            continue

        h1_li = soup.new_tag("li")
        h1_a = soup.new_tag("a", href=f"#{h1['id']}")
        h1_a.string = h1.get_text(strip=True)
        h1_li.append(h1_a)

        h2_entries = section.find_all("h2")
        if h2_entries:
            h2_ul = soup.new_tag("ul")
            for h2 in h2_entries:
                if not h2.get("id"):
                    continue
                h2_li = soup.new_tag("li")
                h2_a = soup.new_tag("a", href=f"#{h2['id']}")
                h2_a.string = h2.get_text(strip=True)
                h2_li.append(h2_a)
                h2_ul.append(h2_li)
            h1_li.append(h2_ul)

        toc_ul.append(h1_li)
        log.info(f"pre_pdf_render: added TOC entry '{h1.get_text(strip=True)[:40]}'")

    return str(soup)


def generate_both_pdfs(config: dict, pdf_scheme: str, schemes: list) -> None:
    """to-pdf が生成した PDF を primary_scheme 版として保存し、
    alternate scheme 版を WeasyPrint で追加生成する。
    """
    site_dir = Path(config["site_dir"])
    site_name = config.get("site_name", "docs")
    primary = pdf_scheme
    alt = "slate" if primary == "default" else "default"

    orig_pdf = site_dir / f"{site_name}.pdf"
    if not orig_pdf.exists():
        log.debug("PDF not found; skipping dual PDF generation")
        return

    primary_pdf = site_dir / f"{site_name}_{primary}.pdf"
    alt_pdf = site_dir / f"{site_name}_{alt}.pdf"
    shutil.copy2(orig_pdf, primary_pdf)

    saved_html = site_dir / "_pdf_source.html"
    if not saved_html.exists():
        log.warning("Saved HTML not found; alternate PDF will not be generated")
        return

    html = saved_html.read_text(encoding="utf-8")

    try:
        pdf_plugin = config.get("plugins", {})["to-pdf"]
    except KeyError:
        return

    template_dir = pdf_plugin._options.custom_template_path
    palette_path = site_dir / "_stylesheets" / "_palette.css"
    orig_palette = (
        palette_path.read_text(encoding="utf-8") if palette_path.exists() else ""
    )

    generate_pdf_styles(template_dir, alt)
    from mkdocs_to_pdf.styles import style_for_print

    alt_print_css = style_for_print(pdf_plugin._options)

    def swap_print_style(m: re.Match) -> str:
        return (
            f"{m.group(1)}{alt_print_css}{m.group(3)}"
            if "string-set:" in m.group(2)
            else m.group(0)
        )

    alt_html = re.sub(
        r"(<style[^>]*>)(.*?)(</style>)", swap_print_style, html, flags=re.DOTALL
    )

    orig_logo = PDF_LOGO_CONFIG[primary]["cover_logo"]
    alt_logo = PDF_LOGO_CONFIG[alt]["cover_logo"]
    alt_html = alt_html.replace(orig_logo, alt_logo)

    primary_fill = (
        "rgba(255,255,255,0.54)" if primary == "slate" else "rgba(0,0,0,0.54)"
    )
    alt_fill = "rgba(0,0,0,0.54)" if primary == "slate" else "rgba(255,255,255,0.54)"
    alt_html = alt_html.replace(f"fill: {primary_fill}", f"fill: {alt_fill}")

    from bs4 import BeautifulSoup as _BS

    alt_soup = _BS(alt_html, "html.parser")
    alt_text_fill = "rgba(255,255,255,0.82)" if alt == "slate" else "rgba(0,0,0,0.87)"
    fix_converted_inline_icon_fill(alt_soup, alt_text_fill)
    log.info(f"Alternate PDF ({alt}): inline icon fill set to {alt_text_fill}")

    grid_alt_fill = "#ffffff" if alt == "default" else "#1a1a1a"
    fix_converted_twemoji_fill(alt_soup, grid_alt_fill)
    log.info(f"Alternate PDF ({alt}): grid card title icon fill set to {grid_alt_fill}")

    arrow_alt_fill = next(
        (p["main"] for s, p, _ in schemes if s == alt),
        "#00838F",
    )
    fix_converted_arrow_fill(alt_soup, arrow_alt_fill)
    log.info(f"Alternate PDF ({alt}): arrow icon fill set to {arrow_alt_fill}")
    alt_html = str(alt_soup)

    images_dir = site_dir / "images"
    png_backups: list = []
    if images_dir.exists():
        for default_png in images_dir.glob("*_mermaid_*_default.png"):
            stem = default_png.stem[: -len("_default")]
            orig_png = images_dir / f"{stem}.png"
            slate_png = images_dir / f"{stem}_slate.png"
            if orig_png.exists() and slate_png.exists():
                backup = images_dir / f"{stem}.png.bak"
                shutil.copy2(orig_png, backup)
                shutil.copy2(slate_png if alt == "slate" else default_png, orig_png)
                png_backups.append((orig_png, backup))

    try:
        palette_path.write_text(build_palette_css(schemes, alt), encoding="utf-8")
        import weasyprint

        weasyprint.HTML(string=alt_html).write_pdf(str(alt_pdf))
        log.info(f"Alternate PDF ({alt}) generated: {alt_pdf.name}")
    except Exception as e:
        log.error(f"Alternate PDF generation failed: {e}")
    finally:
        palette_path.write_text(orig_palette, encoding="utf-8")
        generate_pdf_styles(template_dir, primary)
        for orig_png, backup in png_backups:
            if backup.exists():
                shutil.copy2(backup, orig_png)
                backup.unlink()
        saved_html.unlink(missing_ok=True)

    orig_pdf.unlink(missing_ok=True)
    log.info(f"Dual PDFs ready: {primary_pdf.name}, {alt_pdf.name}")
